export const CREATETIMER = 'CREATETIMER';

export const INPUTCHANGE = 'INPUTCHANGE';

export const CLEARINPUTS = 'CLEARINPUTS';

export const UPDATECURRENTDATE = 'UPDATECURRENTDATE';

export const DELETETIMER = 'DELETETIMER';
